spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

logging.level.org.springframework.security=INFO

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

api.security.token.secret=${JWT_SECRET}
api.security.refresh-token.expiration-days=${REFRESH_TOKEN_EXPIRATION_DAYS:30}
api.security.refresh-token.cookie-secure=true

app.frontend.base-url=${BASE_URL_FRONT}

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.debug=false

pluggy.base-url=${PLUGGY_BASE_URL:https://api.pluggy.ai}
pluggy.client-id=${PLUGGY_CLIENT_ID}
pluggy.client-secret=${PLUGGY_CLIENT_SECRET}
pluggy.api-key=${PLUGGY_API_KEY:}
